version: '3.1'

services:

  # Reverse proxy / router
  traefik:
    image: ${ROUTER_IMAGE:-}
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - ${NETWORK_NAME:-}
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`${ROUTER_HOST:-}`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${BASIC_AUTH_USER:-}:${BASIC_AUTH_PASS:-}"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.routers.traefik.service=api@internal"

  # Docker UI
  portainer:
    image: ${DOCKER_UI_IMAGE:-}
    command: --no-auth -H unix:///var/run/docker.sock
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - ${NETWORK_NAME:-}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`${DOCKER_UI_HOST:-}`)"
      - "traefik.http.middlewares.portainer-auth.basicauth.users=${BASIC_AUTH_USER:-}:${BASIC_AUTH_PASS:-}"
      # Redirect to https.
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`${DOCKER_UI_HOST:-}`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.tls.certresolver=http"
      - "traefik.http.routers.portainer-secure.service=portainer"
      - "traefik.http.routers.portainer-secure.middlewares=portainer-auth"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.docker.network=${NETWORK_NAME:-}"

  # DB Admin.
  pma:
    image: ${DB_UI_IMAGE:-}
    networks:
      - ${NETWORK_NAME:-}
    container_name: pma
    restart: unless-stopped
    environment:
      PMA_HOST: ${DB_HOST:-}
      PMA_USER: ${DB_UI_USER:-}
      PMA_PASSWORD: ${DB_UI_PASS:-}
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma.rule=Host(`${DB_UI_HOST:-}`)"
      - "traefik.http.routers.pma.service=pma"
      - "traefik.http.services.pma.loadbalancer.server.port=80"
      - "traefik.http.middlewares.pma-auth.basicauth.users=${BASIC_AUTH_USER:-}:${BASIC_AUTH_PASS:-}"
      - "traefik.http.routers.pma.middlewares=pma-auth"

networks:
  gateway:
    external: true
