version: '2.3'

services:

  # Example building a custom image
  # Run dokcer-compose -d --build up
  cli:
    build:
      context: .
      dockerfile: $PWD/Dockerfile.custom
      args:
        PROJECT_VERSION: ${PROJECT_VERSION:-^1.0}
        CLIENT_SECRET: ${CLIENT_SECRET:-}
    # Output image name (see docker images)    
    image: example/myproject-cli 
    networks:
      - gateway
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`website-build.example.local`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

  
networks:
   gateway:
    external: true
